env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
  no-console: 0
  indent: ["error", 4]
  react/jsx-indent: ["error", 4]
  react/jsx-indent-props: ["error", 4]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  